services:
  app:
    image: python:3.11-slim
    working_dir: /app
    ports:
      - 8099:8099
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && python app.py"
    depends_on:
      - web
  bot:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && python bot.py"
  web:
    image: node:20.11.0
    working_dir: /web
    ports:
      - 5173:5173
    volumes:
      - ./web:/web
      - /web/node_modules
      - /web/dist
    command: sh -c "npm i && npm start"
  