import marvel

mdb = marvel.Marvel()

session = mdb.session()
session.execute("DROP TABLE marvel.users")
session.execute("DROP TABLE marvel.heroes")
session.execute("DROP TABLE marvel.pools")

mdb.run_schema()
mdb.add_user('user')
user = mdb.get_user('user')
print(user)
mdb.add_hero('user', 'hero')
mdb.add_hero('user', 'hero')
mdb.add_hero('user', 'hero')
mdb.add_hero('user', 'hero')
mdb.add_hero('user', 'hero1')
mdb.add_hero('user', 'hero2')
heroes = mdb.get_heroes('user')
print(heroes)
hero = mdb.get_hero('user', 'hero')
print(hero)
mdb.add_pool(hero.id)
pool = mdb.get_pool(hero.id)
print(pool)
